### ISSUE TITLE
调查：禁止访问 heroku 网站的地区和线路

### ISSUE THREAD

**Issue by 521xueweihan** [521xueweihan/shadowsocks-heroku#21]
在不挂代理的情况下，有的线路已经无法正常登陆 heroku 的登陆页。有哪些小伙伴又跟我一样的情况吗？

- 需要挂代理：
    - 北京移动的宽带
- 不需要挂代理：
    - 北京市 鹏博士宽带

**Comment by zhmglp** [comment]
小白一个，一步一步完全按照教程做好，最后一步出错，：node local.js -s 你的app名称.herokuapp.com -l 1080 -m 设置的加密算法 -k 设置的密码 -r 80（名，加密和密码都改自己的设置了）  出现以下信息：
module.js:472
    throw err;
    ^

Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Temp\shadowsocks-heroku-master\local.
js:15:15)
    at Object.<anonymous> (C:\Temp\shadowsocks-heroku-master\local.
js:322:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

请教521xueweihan，这是哪里出错了。谢谢。

**Comment by zhmglp** [comment]
广东要代理。

**Comment by 521xueweihan** [comment]
@zhmglp 那请问，你是使用了什么代理软甲？

**Comment by zhmglp** [comment]
firefox插件。    还有刚刚我的问题怎么被删除了呢？

**Comment by 521xueweihan** [comment]
@zhmglp 这里是讨论被禁用地区的问题，有问题，请另起 issue

**Comment by zhmglp** [comment]
不好意思，小白一个，也不懂这里的规矩，而且e文死菜，看到回复框就回了。

**Comment by uragasit** [comment]
北京宽带通，不能直连，好像用的是内蒙古电信

**Comment by drbacon** [comment]
用了vpn也上不了https://id.heroku.com/
求助
@上海

**Comment by neila-a** [comment]
只能访问heroku.com，不能访问id.heroku.com。
@江西
